### ISSUE TITLE
補間曲線パレットのパレットを閉じるとMMDが落ちる

### ISSUE THREAD

**Issue by mikosu3** [oigami/MMDUtility#1]
MMDを立ち上げた後、補間曲線パレットをオンにし、
保管曲線パレットの右上の☓ボタンを押すとMMDが強制終了します。

環境
----------------------------
- Windows 7 64bit
- MikuMikuDance 9.20 64bit
- MMDPlugin ver0.36
- MMDUtility ver0.08
----------------------------

また、使い方が詳しく書いてなかったのでよく解らないのですが正常に動作していないように思います。
キーフーレームを選択後、パレットの数字を押す
　→ 無反応
保管曲線設定ウィンドウの1にチェックを入れた状態でMMDの保管曲線を変更、
新しくキーフレームを打った後、保管曲線パレットの1ボタンを押下
　→ 無反応

使い方が間違っている場合はご教授ください

**Comment by oigami** [comment]
> 環境
> 
> Windows 7 64bit
> MikuMikuDance 9.20 64bit

MikuMikuDance 9.26 64bit で試してもらえますか。

**Comment by mikosu3** [comment]
MikuMikuDance 9.26 64bit に上げた所、強制終了しないようになりました。
また、パレットの数字押下で保管曲線も変更できました。
9.20ではそもそも動作していなかったようです。
