### ISSUE TITLE
Can't open MMD after Install MMDUtility

### ISSUE THREAD

**Issue by buidoi8x** [oigami/MMDUtility#4]
Thank you for Plugin.
But I had a error. after I installed MMDplugin and MMDUtility. When I opened MMD.exe I got error " System32/d3d9.dll の□-ド仁失敗しました"
like picture: http://i.imgur.com/s00Dy0D.png

Could You help me fix this?
Thanks

**Comment by oigami** [comment]
Thank you for reporting.
I fixed the absolute path of d3d9.dll to relative path.
When you restart the installer, you can download MMDPlugin ver0.37. please install it.

**Comment by buidoi8x** [comment]
Thank You so much.
It works well now.
Thanks
