### ISSUE TITLE
MMDPluginInstallerが最新バージョンで使用できない件について

### ISSUE THREAD

**Issue by mf-Mii** [oigami/MMDUtility#5]
最新のMMD(Ver.9.31)で、Installerが使用できません
可能であれば修正をお願いします

**Comment by PTOM76** [comment]
私が試したところ、MMDUtilityとMMDPlugin自体は最新バージョンでも動作するみたいです。
MMDPluginを「 https://bowlroll.net/file/121761 」からダウンロードし、d3d9.dll、d3dx9_43.dll、MMDPlugin.dllをすべてMikuMikuDance.exeの入っているディレクトリに入れ、「 https://bowlroll.net/file/121762 」の解凍したフォルダのpluginの中にあるMMDUtilityをPluginフォルダに入れると使えました。
