### ISSUE TITLE
doesn't work with mmd 9.32

### ISSUE THREAD

**Issue by Rawrgurl** [oigami/MMDUtility#6]
the latest version of the plugin installer doesn't work with mmd 9.32 I cannot install the installer to get and use MMDUtility. will there be an update soon?

**Comment by PTOM76** [comment]
It's unofficial because I forked to the latest version, but I tried to fix it.
I hope the official one will respond someday.
https://github.com/PTOM76/MMDPluginInstallManager

**Comment by Rawrgurl** [comment]
i tried unsuccessfully to install it into 9.26 is there a later version that works.
